trigger:
- main # ou sua branch principal

pool:
  name: 'Agent pool SBR' 

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.14' # Defina a versão do Python
    addToPath: true

- script: |
    python -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
    python manage.py collectstatic --noinput
  displayName: 'Instalar Dependências e Coletar Estáticos'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Microsoft Partner Network(b372c16a-8b32-4bf7-adb9-1d8f74d2d1dc)'
    appType: 'webAppLinux'
    appName: 'sistemasbrkb'
    package: '$(System.DefaultWorkingDirectory)'
